name: imovie_app
description: "A new Flutter project."
version: 1.0.0+1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev



environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.3
  http: ^1.1.2
  google_fonts: ^5.1.0
  shimmer: ^3.0.0
  youtube_player_flutter: ^9.0.1
  intl: ^0.19.0
  url_launcher: ^6.3.0
  flutter_dotenv: ^5.1.0
  firebase_core: ^3.3.0
  firebase_remote_config: ^5.0.4
  firebase_crashlytics: ^4.0.4
  firebase_auth: ^5.1.4
  image_picker: ^1.1.2
  flutter_animate: ^4.5.0
  onesignal_flutter: ^5.2.2
  google_sign_in: ^6.2.1
  local_auth: ^2.2.0
  lottie: ^3.1.2
  shared_preferences: ^2.3.1
  avatar_glow: ^3.0.1
  speech_to_text: ^6.6.0
  


  cupertino_icons: ^1.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true


  assets:
    - assets/images/

