// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuEO8H3v3Cg_C5JC2jNqMumnzo6feDDW0',
    appId: '1:1076756629279:web:45d570d1f9fc77457a122a',
    messagingSenderId: '1076756629279',
    projectId: 'i-movie-e0d88',
    authDomain: 'i-movie-e0d88.firebaseapp.com',
    storageBucket: 'i-movie-e0d88.appspot.com',
    measurementId: 'G-T01R0V80Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvtJy-UccD0OUeKRGny-4rCSRP56mRPCc',
    appId: '1:1076756629279:android:86cbb98f8e2337f47a122a',
    messagingSenderId: '1076756629279',
    projectId: 'i-movie-e0d88',
    storageBucket: 'i-movie-e0d88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWJvmNXIX8swpYn5CW0AznpO72wH_7uv0',
    appId: '1:1076756629279:ios:2999584cd620951a7a122a',
    messagingSenderId: '1076756629279',
    projectId: 'i-movie-e0d88',
    storageBucket: 'i-movie-e0d88.appspot.com',
    iosBundleId: 'com.romolo.imovie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWJvmNXIX8swpYn5CW0AznpO72wH_7uv0',
    appId: '1:1076756629279:ios:2999584cd620951a7a122a',
    messagingSenderId: '1076756629279',
    projectId: 'i-movie-e0d88',
    storageBucket: 'i-movie-e0d88.appspot.com',
    iosBundleId: 'com.romolo.imovie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuEO8H3v3Cg_C5JC2jNqMumnzo6feDDW0',
    appId: '1:1076756629279:web:26881f03f43e47287a122a',
    messagingSenderId: '1076756629279',
    projectId: 'i-movie-e0d88',
    authDomain: 'i-movie-e0d88.firebaseapp.com',
    storageBucket: 'i-movie-e0d88.appspot.com',
    measurementId: 'G-HC51KXYXR4',
  );
}
